-- Migration 011: Backfill website URLs for all colleges added without websites

UPDATE colleges SET website = 'https://wfu.edu' WHERE name = 'Wake Forest University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://rochester.edu' WHERE name = 'University of Rochester' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://case.edu' WHERE name = 'Case Western Reserve University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://brandeis.edu' WHERE name = 'Brandeis University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://rpi.edu' WHERE name = 'Rensselaer Polytechnic Institute' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://wpi.edu' WHERE name = 'Worcester Polytechnic Institute' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://miami.edu' WHERE name = 'University of Miami' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://fordham.edu' WHERE name = 'Fordham University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://villanova.edu' WHERE name = 'Villanova University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://lehigh.edu' WHERE name = 'Lehigh University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://wustl.edu' WHERE name = 'Washington University in St. Louis' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://bc.edu' WHERE name = 'Boston College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://gatech.edu' WHERE name = 'Georgia Institute of Technology' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://gwu.edu' WHERE name = 'George Washington University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://american.edu' WHERE name = 'American University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://syr.edu' WHERE name = 'Syracuse University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://pepperdine.edu' WHERE name = 'Pepperdine University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://scu.edu' WHERE name = 'Santa Clara University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://gonzaga.edu' WHERE name = 'Gonzaga University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://lmu.edu' WHERE name = 'Loyola Marymount University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://du.edu' WHERE name = 'University of Denver' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://creighton.edu' WHERE name = 'Creighton University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://marquette.edu' WHERE name = 'Marquette University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://richmond.edu' WHERE name = 'University of Richmond' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://tcu.edu' WHERE name = 'Texas Christian University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://baylor.edu' WHERE name = 'Baylor University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://pomona.edu' WHERE name = 'Pomona College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://middlebury.edu' WHERE name = 'Middlebury College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://carleton.edu' WHERE name = 'Carleton College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://colby.edu' WHERE name = 'Colby College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://bates.edu' WHERE name = 'Bates College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://hamilton.edu' WHERE name = 'Hamilton College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://haverford.edu' WHERE name = 'Haverford College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://vassar.edu' WHERE name = 'Vassar College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://colgate.edu' WHERE name = 'Colgate University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://davidson.edu' WHERE name = 'Davidson College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://oberlin.edu' WHERE name = 'Oberlin College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://hmc.edu' WHERE name = 'Harvey Mudd College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://cmc.edu' WHERE name = 'Claremont McKenna College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://scrippscollege.edu' WHERE name = 'Scripps College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://pitzer.edu' WHERE name = 'Pitzer College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://barnard.edu' WHERE name = 'Barnard College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://trincoll.edu' WHERE name = 'Trinity College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://bucknell.edu' WHERE name = 'Bucknell University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://lafayette.edu' WHERE name = 'Lafayette College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://dickinson.edu' WHERE name = 'Dickinson College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://fandm.edu' WHERE name = 'Franklin and Marshall College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://grinnell.edu' WHERE name = 'Grinnell College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://macalester.edu' WHERE name = 'Macalester College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://coloradocollege.edu' WHERE name = 'Colorado College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://reed.edu' WHERE name = 'Reed College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://whitman.edu' WHERE name = 'Whitman College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://oxy.edu' WHERE name = 'Occidental College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://skidmore.edu' WHERE name = 'Skidmore College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://union.edu' WHERE name = 'Union College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://sarahlawrence.edu' WHERE name = 'Sarah Lawrence College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://bard.edu' WHERE name = 'Bard College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://brynmawr.edu' WHERE name = 'Bryn Mawr College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://gettysburg.edu' WHERE name = 'Gettysburg College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://muhlenberg.edu' WHERE name = 'Muhlenberg College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://umd.edu' WHERE name = 'University of Maryland' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://umn.edu' WHERE name = 'University of Minnesota' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://uga.edu' WHERE name = 'University of Georgia' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://arizona.edu' WHERE name = 'University of Arizona' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://clemson.edu' WHERE name = 'Clemson University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://vt.edu' WHERE name = 'Virginia Tech' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://wm.edu' WHERE name = 'College of William and Mary' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://pitt.edu' WHERE name = 'University of Pittsburgh' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://uconn.edu' WHERE name = 'University of Connecticut' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://umass.edu' WHERE name = 'University of Massachusetts Amherst' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://udel.edu' WHERE name = 'University of Delaware' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://uiowa.edu' WHERE name = 'University of Iowa' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://utah.edu' WHERE name = 'University of Utah' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://colostate.edu' WHERE name = 'Colorado State University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://jmu.edu' WHERE name = 'James Madison University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://sc.edu' WHERE name = 'University of South Carolina' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://lsu.edu' WHERE name = 'Louisiana State University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://drexel.edu' WHERE name = 'Drexel University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://temple.edu' WHERE name = 'Temple University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://uvm.edu' WHERE name = 'University of Vermont' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://stonybrook.edu' WHERE name = 'Stony Brook University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://ku.edu' WHERE name = 'University of Kansas' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://stevens.edu' WHERE name = 'Stevens Institute of Technology' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://rit.edu' WHERE name = 'Rochester Institute of Technology' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://babson.edu' WHERE name = 'Babson College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://bentley.edu' WHERE name = 'Bentley University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://elon.edu' WHERE name = 'Elon University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://fairfield.edu' WHERE name = 'Fairfield University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://providence.edu' WHERE name = 'Providence College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://quinnipiac.edu' WHERE name = 'Quinnipiac University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://sacredheart.edu' WHERE name = 'Sacred Heart University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://kenyon.edu' WHERE name = 'Kenyon College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://denison.edu' WHERE name = 'Denison University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://wooster.edu' WHERE name = 'College of Wooster' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://depauw.edu' WHERE name = 'DePauw University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://owu.edu' WHERE name = 'Ohio Wesleyan University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://butler.edu' WHERE name = 'Butler University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://furman.edu' WHERE name = 'Furman University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://wofford.edu' WHERE name = 'Wofford College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://rhodes.edu' WHERE name = 'Rhodes College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://sewanee.edu' WHERE name = 'Sewanee: The University of the South' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://centre.edu' WHERE name = 'Centre College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://trinity.edu' WHERE name = 'Trinity University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://agnesscott.edu' WHERE name = 'Agnes Scott College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://wheatonma.edu' WHERE name = 'Wheaton College (Massachusetts)' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://wheaton.edu' WHERE name = 'Wheaton College (Illinois)' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://hope.edu' WHERE name = 'Hope College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://allegheny.edu' WHERE name = 'Allegheny College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://hendrix.edu' WHERE name = 'Hendrix College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://howard.edu' WHERE name = 'Howard University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://spelman.edu' WHERE name = 'Spelman College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://morehouse.edu' WHERE name = 'Morehouse College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://hamptonu.edu' WHERE name = 'Hampton University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://cau.edu' WHERE name = 'Clark Atlanta University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://fisk.edu' WHERE name = 'Fisk University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://uci.edu' WHERE name = 'UC Irvine' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://ucsc.edu' WHERE name = 'UC Santa Cruz' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://ucr.edu' WHERE name = 'UC Riverside' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://calpoly.edu' WHERE name = 'Cal Poly San Luis Obispo' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://ncsu.edu' WHERE name = 'NC State University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://ucf.edu' WHERE name = 'University of Central Florida' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://usf.edu' WHERE name = 'University of South Florida' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://iastate.edu' WHERE name = 'Iowa State University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://k-state.edu' WHERE name = 'Kansas State University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://unl.edu' WHERE name = 'University of Nebraska-Lincoln' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://missouri.edu' WHERE name = 'University of Missouri' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://ou.edu' WHERE name = 'University of Oklahoma' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://okstate.edu' WHERE name = 'Oklahoma State University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://uark.edu' WHERE name = 'University of Arkansas' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://auburn.edu' WHERE name = 'Auburn University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://uky.edu' WHERE name = 'University of Kentucky' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://olemiss.edu' WHERE name = 'University of Mississippi' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://msstate.edu' WHERE name = 'Mississippi State University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://uc.edu' WHERE name = 'University of Cincinnati' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://miamioh.edu' WHERE name = 'Miami University Ohio' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://ohio.edu' WHERE name = 'Ohio University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://unh.edu' WHERE name = 'University of New Hampshire' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://uri.edu' WHERE name = 'University of Rhode Island' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://slu.edu' WHERE name = 'Saint Louis University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://luc.edu' WHERE name = 'Loyola University Chicago' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://depaul.edu' WHERE name = 'DePaul University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://udayton.edu' WHERE name = 'University of Dayton' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://xavier.edu' WHERE name = 'Xavier University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://shu.edu' WHERE name = 'Seton Hall University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://hofstra.edu' WHERE name = 'Hofstra University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://pugetsound.edu' WHERE name = 'University of Puget Sound' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://lclark.edu' WHERE name = 'Lewis and Clark College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://seattleu.edu' WHERE name = 'Seattle University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://usfca.edu' WHERE name = 'University of San Francisco' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://sandiego.edu' WHERE name = 'University of San Diego' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://willamette.edu' WHERE name = 'Willamette University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://unlv.edu' WHERE name = 'University of Nevada Las Vegas' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://unr.edu' WHERE name = 'University of Nevada Reno' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://boisestate.edu' WHERE name = 'Boise State University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://uidaho.edu' WHERE name = 'University of Idaho' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://uwyo.edu' WHERE name = 'University of Wyoming' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://unm.edu' WHERE name = 'University of New Mexico' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://hawaii.edu' WHERE name = 'University of Hawaii at Manoa' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://mines.edu' WHERE name = 'Colorado School of Mines' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://iit.edu' WHERE name = 'Illinois Institute of Technology' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://njit.edu' WHERE name = 'New Jersey Institute of Technology' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://sdsu.edu' WHERE name = 'San Diego State University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://csulb.edu' WHERE name = 'Cal State Long Beach' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://fiu.edu' WHERE name = 'Florida International University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://ncat.edu' WHERE name = 'North Carolina A&T State University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://morgan.edu' WHERE name = 'Morgan State University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://famu.edu' WHERE name = 'Florida A&M University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://xula.edu' WHERE name = 'Xavier University of Louisiana' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://stmarys-ca.edu' WHERE name = 'Saint Mary''s College of California' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://up.edu' WHERE name = 'University of Portland' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://pacific.edu' WHERE name = 'University of the Pacific' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://rollins.edu' WHERE name = 'Rollins College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://belmont.edu' WHERE name = 'Belmont University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://montana.edu' WHERE name = 'Montana State University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://und.edu' WHERE name = 'University of North Dakota' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://ndsu.edu' WHERE name = 'North Dakota State University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://umaine.edu' WHERE name = 'University of Maine' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://anselm.edu' WHERE name = 'Saint Anselm College' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://indiana.edu' WHERE name = 'Indiana University Bloomington' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://illinois.edu' WHERE name = 'University of Illinois Urbana-Champaign' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://wisc.edu' WHERE name = 'University of Wisconsin-Madison' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://utexas.edu' WHERE name = 'University of Texas at Austin' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://tamu.edu' WHERE name = 'Texas A&M University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://uw.edu' WHERE name = 'University of Washington' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://uoregon.edu' WHERE name = 'University of Oregon' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://colorado.edu' WHERE name = 'University of Colorado Boulder' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://asu.edu' WHERE name = 'Arizona State University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://purdue.edu' WHERE name = 'Purdue University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://msu.edu' WHERE name = 'Michigan State University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://rutgers.edu' WHERE name = 'Rutgers University' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://ucsd.edu' WHERE name = 'UC San Diego' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://ucsb.edu' WHERE name = 'UC Santa Barbara' AND (website IS NULL OR website = '');
UPDATE colleges SET website = 'https://ucdavis.edu' WHERE name = 'UC Davis' AND (website IS NULL OR website = '');
